config/routes.rb
Rails.application.routes.draw do
  resources :dogs, only: [:index, :show]
  resources :purchases, only: [:new, :create]
  resources :purchases_dogs, only: [:index, :create] do
    collection do
      get :add_to_cart
    end
  end

  root  'dogs#index'
end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates :name, presence: true

  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :breed_id, :color, :amount, :age, :gender, :size, :photo, presence: true

  belongs_to :breed
  has_many :purchases_dogs

  enum size: {
    mini: "Mini",
    small: "Pequeno Porte",
    medium: "Médio Porte",
    big: "Grande Porte"
  }
  enum gender: {
    m: "Macho",
    f: "Fêmea"
  }

  def self.search(search)
    if search.present?
      joins(:breed)
      .where("LOWER(breeds.name) LIKE LOWER(?)", "%#{search}%")
    else
      where(nil)
    end
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  validates :name, :registry_number, :email, :address, :address_number, :city, :state, :cep, presence: true

  has_many :purchases_dogs

  attr_accessor :dog_id
end

app/models/purchases_dog.rb
class PurchasesDog < ActiveRecord::Base
  validates :dog_id, :purchase_id, :quantity, :total_amount, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  belongs_to :dog
  belongs_to :purchase

  before_validation :calculate_total_amount

  private
    def calculate_total_amount
      self.total_amount = dog.amount * quantity
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: :show

  def index
    @dogs = Dog.search(params[:search])
  end

  def show
  end

  private
    def set_dog
      @dog = Dog.find_by(id: params[:id])
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def new
    @purchase = Purchase.new(dog_id: params[:dog_id])
  end

  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to add_to_cart_purchases_dogs_path(dog_id: @purchase.dog_id, purchase_id: @purchase) }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, alert: @purchase.errors.full_messages }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def purchase_params
      params.require(:purchase).permit(:dog_id, :name, :registry_number, :email, :address,
            :address_number, :complement, :city, :state, :cep)
    end
end

app/controllers/purchases_dogs_controller.rb
class PurchasesDogsController < ApplicationController

  def index
    @purchases_dogs = Cart.new(session)
  end

  def add_to_cart
    @purchases_dogs = Cart.new(session, params[:purchase_id])
    @purchases_dogs.add_dog_to_cart_hash(params[:dog_id])
    redirect_to purchases_dogs_path
  end

  def create
    @purchases_dogs = Cart.new(session)

    respond_to do |format|
      if @purchases_dogs.save_cart
        format.html { redirect_to dogs_path, notice: 'Sua compra foi efetuada com sucesso' }
        format.json { render :show, status: :created }
      else
        format.html { render :index, alert: 'Ocorreu um erro ao processar compra' }
        format.json { render json: 'Ocorreu um erro ao processar compra',  status: :unprocessable_entity }
      end
    end
  end

  private
    def purchases_dog_params
      params.require(:purchases_dog).permit(:quantity, :dog_id, :purchase_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = :success if type.to_sym == :notice
      type = :danger  if type.to_sym == :alert
      text = content_tag(:div,
                         content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                         message.split("\n").join("<br/>").html_safe, :class => "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_list.html.erb
<% @dogs.in_groups_of(3, false) do |dogs_group| %>
  <div class="row">
    <% dogs_group.each do |dog| %>
      <%= link_to dog, class: "fancybox" do %>
        <div class="col-md-4">
          <div class="box-cachorro">
            <%= image_tag dog.photo.url, alt: "#{dog.breed.name.capitalize} #{dog.color.capitalize}"%>
            <div class="btn-foto">Leva eu!</div>
            <div>
              <span class="titulo-cachorro"><%= "#{dog.breed.name} #{dog.color}" %></span>
              <span class="detalhes-cachorro"><strong><%= number_to_currency(dog.amount) %></strong><br><%= pluralize(dog.age, "Ano", "Anos") %> </span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/dogs/index.html.erb
<div class="content">
  <%= render_bootstrap_flash %>
  <div class="container">
    <div id='dogs-list'>
      <%= render partial: 'list' %>
    </div>
  </div>
</div>

app/views/dogs/index.js.erb
$("#dogs-list").html('<%= escape_javascript(render("list")) %>');

app/views/dogs/show.html.erb
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @dog.photo.url, alt: "#{@dog.breed.name.capitalize} #{@dog.color.capitalize}", class: "dog-photo"%>
      </div>
      <div class="col-md-4">
        <div class="box-cachorro">
          <span class="titulo-cachorro"><%= "#{@dog.breed.name} #{@dog.color}" %></span>
        </div>
        <div class="ficha-cachorro">
          <p><strong>Raça:</strong> <%= @dog.breed.name %></p>
          <p><strong>Cor:</strong> <%= @dog.color %></p>
          <p><strong>Idade:</strong> <%= pluralize(@dog.age, 'Ano', 'Anos') %> </p>
          <p><strong>Sexo:</strong> <%= Dog.genders[@dog.gender] %></p>
          <p><strong>Tamanho:</strong> <%= Dog.sizes[@dog.size] %></p>
          <p><strong>Valor:</strong><%= number_to_currency(@dog.amount) %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 col-md-offset-6">
        <% if session['purchase'].nil? %>
          <%= link_to "Levar!", new_purchase_path(dog_id: @dog.id) , class: "btn-go-buy" %>
        <% else %>
          <%= link_to "Levar!", add_to_cart_purchases_dogs_path(dog_id: @dog.id) , class: "btn-go-buy" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <ul class="list-group lista-links">
                    <li class="list-group-item"><a href="#" title="mini">mini</a></li>
                    <li class="list-group-item"><a href="#" title="pequeno porte">pequeno porte</a></li>
                    <li class="list-group-item"><a href="#" title="médio porte">médio porte</a></li>
                    <li class="list-group-item"><a href="#" title="grande porte">grande porte</a></li>
                </ul>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4">
                <ul class="list-group lista-links">
                    <li class="list-group-item"><a href="#" title="até R$100">até R$100</a></li>
                    <li class="list-group-item"><a href="#" title="de R$100 a R$300">de R$100 a R$300</a></li>
                    <li class="list-group-item"><a href="#" title="de R$300 a R$500">de R$300 a R$500</a></li>
                    <li class="list-group-item"><a href="#" title="acima de R$500">acima de R$500</a></li>
                </ul>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4 text-right">
                <%= image_tag "logo-rodape.png", alt: "Charlie & Dogs" %>
                <br>
                <p class="telefone">11 0000.0000<br>
                <a href="mailto:#" title="Entre em contato!">contato@charlieedog.com.br</a></p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_search.html.erb
<!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2">
              <%= link_to image_tag("logo.svg", alt: "Charlie & Dogs"), root_path, title: "Charlie & Dogs" %>
            </div>
            <div class="col-lg-10 col-md-10 col-sm-10">
              <%= form_tag dogs_path, method: "get", id: "dogs_search", remote: true do %>
                <div class="input-group buscar">
                  <%= text_field_tag :search, params[:search], class: "form-control input-lg", placeholder: "Buscar por..."%>
                  <span class="input-group-btn">
                    <button class="btn btn-default input-lg" type="button"><span class="glyphicon glyphicon-search"></span></button>
                  </span>
                </div>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Charlie & Dog</title>
    <meta name="description" content="Na Charlie & Dog você com certeza encontra o seu próximo melhor amigo">
    <meta name="viewport" content="width=device-width">

    <link href='http://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>

    <%= javascript_include_tag "jquery-1.10.1.min.js"%>
    <%= javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min.js"%>
    <%= javascript_include_tag "jquery.fancybox.pack.js"%>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
      <![endif]-->

    <%= render partial: "layouts/search"%>

    <%= yield %>

    <%= render partial: "layouts/footer"%>

  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2>Ocorreram os seguintes erros ao efetuar cadastro:</h2>

      <ul>
        <% @purchase.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :dog_id, value: @purchase.dog_id %>

  <div class="title">
    <p> Por favor, entre com seus dados pessoas para continuar a compra </p>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:name) %></label>
    <div class="col-sm-8">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:registry_number) %></label>
    <div class="col-sm-8">
      <%= f.text_field :registry_number, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:email) %></label>
    <div class="col-sm-8">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:address) %></label>
    <div class="col-sm-8">
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:address_number) %></label>
    <div class="col-sm-8">
      <%= f.text_field :address_number, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:complement) %></label>
    <div class="col-sm-8">
      <%= f.text_field :complement, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:city) %></label>
    <div class="col-sm-8">
      <%= f.text_field :city, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:state) %></label>
    <div class="col-sm-8">
      <%= f.text_field :state, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-6 form-group">
    <label class="col-sm-3 control-label"><%= Purchase.human_attribute_name(:cep) %></label>
    <div class="col-sm-8">
      <%= f.text_field :cep, class: 'form-control' %>
    </div>
  </div>

  <div class="col-xs-8 actions">
    <div class="col-md-4 col-md-offset-7">
      <%= f.submit "Continuar...", class: "btn-go-buy" %>
    </div>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchases</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<div class="content">
  <div class="container">
    <%= render 'form' %>
  </div>
</div>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases_dogs/index.html.erb
<div class="content">
  <div class="container">
    <% @purchases_dogs.cart_dogs_hash.each do |dog_id, quantity| %>
      <div class="row">
        <% dog = Dog.find_by(id: dog_id) %>
        <div class="col-xs-4">
          <%= image_tag dog.photo.url, alt: "#{dog.breed.name.capitalize} #{dog.color.capitalize}", class: "dog-photo"%>
        </div>

        <div class="col-xs-8">
          <div class="box-cachorro">
            <span class="titulo-cachorro"><%= "#{dog.breed.name} #{dog.color}" %></span>
          </div>
        </div>

        <div class="col-xs-8">
          <label class="col-sm-1 control-label"><%= Dog.human_attribute_name(:amount) %></label>
          <div class="col-sm-7">
            <%= label_tag :amount, number_to_currency(dog.amount) %>
          </div>
        </div>

        <div class="col-xs-4">
          <label class="col-sm-3 control-label"><%= PurchasesDog.human_attribute_name(:quantity) %></label>
          <div class="col-sm-8">
            <%= label_tag :quantity, quantity %>
          </div>
        </div>

        <div class="col-xs-4">
          <label class="col-sm-4 control-label"><%= PurchasesDog.human_attribute_name(:total_amount) %></label>
          <div class="col-sm-8">
            <%= label_tag :total_amount, number_to_currency(quantity * dog.amount) %>
          </div>
        </div>
      </div>
      <br>
    <% end %>


    <div class="col-xs-10 col-md-offset-1">
      <div class="actions">
        <div class="col-md-5">
          <%= link_to "Continuar Comprando", dogs_path, class: "btn-go-buy", id: "buy-more" %>
        </div>

        <div class="col-md-3 col-md-offset-4">
          <%= link_to "Finalizar!", purchases_dogs_path, method: :post, class: "btn-go-buy" %>
        </div>
      </div>
    </div>
  </div>
</div>